import {change,windowMonths,metricValue,priorYear,compatibleSeries} from './metrics.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,sign=false)=>v==null||!Number.isFinite(v)?'—':`${sign&&v>0?'+':''}${Math.round(v).toLocaleString('ko-KR')}`;
const date=m=>`${m.slice(2,4)}년 ${Number(m.slice(5))}월`,fullDate=m=>`${m.slice(0,4)}년 ${Number(m.slice(5))}월`;
let data,group='전체',favorites=new Set();try{favorites=new Set(JSON.parse(localStorage.getItem('japan-export-favorites')||'[]'))}catch{}
const tooltip=document.createElement('div');tooltip.className='tooltip';document.body.append(tooltip);
const colors=['#657384','#91a5b7','#5B9BD5','#ED7D31','#FFCB05'];
const state=()=>({country:$('#country').value,range:+$('#range').value,metric:$('#metric').value,mode:$('#mode').value,sort:$('#sort').value,query:$('#search').value.toLowerCase().trim()});
function countryName(c){return c==='WORLD'?'세계 전체':data.countries[c]||`국가 코드 ${c}`}
function series(item,c){return item.series[c]||{}}
function val(rows,m,metric){return metric==='yoy'?change(rows[m]?.value,rows[priorYear(m)]?.value):metricValue(rows[m],metric)}
function unit(rows,metric){if(metric==='value')return '억 엔';if(metric==='yoy')return '%';const us=new Set(Object.values(rows).filter(r=>r.quantity!=null).map(r=>r.unit));const u=us.size===1?[...us][0]:'단위 혼합';return metric==='price'?`엔/${u}`:u}
function plot(rows,months,metric,mode){
 const W=1280,H=320,L=75,R=20,T=30,B=42,pw=W-L-R,ph=H-T-B;
 let lines=[],values=[];
 if(mode==='season'){
  const years=[...new Set(months.map(m=>m.slice(0,4)))].slice(-Math.min(5,Math.ceil(months.length/12)));
  lines=years.map((y,i)=>({label:y+'년',color:colors[colors.length-years.length+i],points:Array.from({length:12},(_,j)=>{let m=`${y}-${String(j+1).padStart(2,'0')}`;return {m,v:months.includes(m)?val(rows,m,metric):null}})}));values=lines.flatMap(l=>l.points.map(p=>p.v));
 }else values=months.map(m=>val(rows,m,metric));
 const valid=values.filter(v=>v!=null&&Number.isFinite(v));if(!valid.length)return '<div class="plot-empty">이 국가·지표에 비교 가능한 수치가 없습니다. 수량 단위가 섞이거나 변경된 경우 수량·단가 비교를 표시하지 않습니다.</div>';
 let max=Math.max(0,...valid),min=Math.min(0,...valid);if(max===min)max=min+1;let span=max-min;max+=span*.09;if(min<0)min-=span*.09;
 const y=v=>T+(max-v)/(max-min)*ph,x=(i,n)=>L+(i+.5)/n*pw;
 let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc($('#metric').selectedOptions[0].text)} ${mode==='season'?'연도별 비교':'월별 추이'}"><text x="${L}" y="16">${esc(unit(rows,metric))}</text>`;
 for(let i=0;i<=4;i++){let v=min+(max-min)*i/4,yy=y(v);svg+=`<line x1="${L}" x2="${W-R}" y1="${yy}" y2="${yy}" stroke="#2a3542"/><text x="${L-12}" y="${yy+4}" text-anchor="end">${fmt(v)}</text>`}
 svg+=`<line x1="${L}" x2="${W-R}" y1="${y(0)}" y2="${y(0)}" stroke="#59616c"/>`;
 if(mode==='season'){
  lines.forEach(l=>{let path='',started=false;l.points.forEach((p,i)=>{if(p.v==null){started=false;return}path+=`${started?'L':'M'}${x(i,12)},${y(p.v)} `;started=true});svg+=`<path d="${path}" fill="none" stroke="${l.color}" stroke-width="3"/>`;l.points.forEach((p,i)=>{if(p.v==null)return;let tip=`${fullDate(p.m)} · ${fmt(p.v,metric==='yoy')}${metric==='yoy'?'%':' '+unit(rows,metric)}`;svg+=`<circle cx="${x(i,12)}" cy="${y(p.v)}" r="5" fill="${l.color}" data-tip="${esc(tip)}"><title>${esc(tip)}</title></circle>`})});
  for(let i=0;i<12;i++)svg+=`<text x="${x(i,12)}" y="${H-12}" text-anchor="middle">${i+1}월</text>`;
 }else{
  const bw=pw/months.length*.70;
  months.forEach((m,i)=>{let v=values[i];if(v==null)return;let xx=x(i,months.length),yy=y(v),tip=`${fullDate(m)} · ${fmt(v,metric==='yoy')}${metric==='yoy'?'%':' '+unit(rows,metric)}`;svg+=`<rect class="bar" x="${xx-bw/2}" y="${Math.min(yy,y(0))}" width="${bw}" height="${Math.max(1,Math.abs(y(0)-yy))}" fill="${i===months.length-1?'#FFCB05':v<0?'#5B9BD5':'#5B9BD5'}" opacity="${i===months.length-1?1:.88}" data-tip="${esc(tip)}"><title>${esc(tip)}</title></rect>`;if(i===0||i===months.length-1||i%Math.max(1,Math.floor(months.length/8))===0)svg+=`<text x="${xx}" y="${H-12}" text-anchor="middle">${m.slice(2,4)}.${m.slice(5)}</text>`});
 }
 return svg+'</svg>'+(mode==='season'?`<div class="legend">${lines.map(l=>`<span><i style="background:${l.color}"></i>${l.label}</span>`).join('')}</div>`:'');
}
function rowTable(rows,months,metric){let rev=[...months].reverse();return `<table><thead><tr><th>월별 수치</th>${rev.map((m,i)=>`<th class="${i===0?'latest':''}">${date(m)}</th>`).join('')}</tr></thead><tbody>${[[metric,$('#metric').selectedOptions[0].text],...(metric==='yoy'?[]:[['yoy','전년 대비 (%)']])].map(([met,label])=>`<tr><td>${esc(label)}</td>${rev.map((m,i)=>{let v=val(rows,m,met);return `<td class="${i===0?'latest ':''}${met==='yoy'?(v>0?'positive':v<0?'negative':''):''}">${fmt(v,met==='yoy')}${met==='yoy'&&v!=null?'%':''}</td>`}).join('')}</tr>`).join('')}</tbody></table>`}
function panel(item,s,months){const rows=compatibleSeries(series(item,s.country),months),last=data.latestMonth,r=rows[last],prev=windowMonths(last,2)[0],yoy=change(r?.value,rows[priorYear(last)]?.value),mom=change(r?.value,rows[prev]?.value);const countries=Object.entries(item.series).filter(([c])=>c!=='WORLD').map(([c,rs])=>({c,v:rs[last]?.value??0})).sort((a,b)=>b.v-a.v).slice(0,10);let recent=months.filter(m=>rows[m]?.value!=null).length;
 return `<article class="panel" id="${item.id}"><div class="panelhead"><div><div class="eyebrow">${esc(item.group)} / HS ${esc(item.hs.join(' · '))}</div><h2>${esc(item.name)}</h2></div><button class="smallbtn ${favorites.has(item.id)?'on':''}" data-fav="${item.id}" aria-label="${esc(item.name)} 관심 품목 ${favorites.has(item.id)?'해제':'추가'}" aria-pressed="${favorites.has(item.id)}">${favorites.has(item.id)?'★':'☆'}</button></div><p class="panelnote">${esc(item.note)}</p><div class="chart">${plot(rows,months,s.metric,s.mode)}</div><div class="kpis"><div class="kpi"><div class="kpi-label">${date(last)} · ${esc(countryName(s.country))}</div><div class="kpi-value">${fmt(r?.value==null?null:r.value/100000)}<span class="kpi-unit">억 엔</span></div></div><div class="kpi"><div class="kpi-label">전년 동월 대비</div><div class="kpi-value ${yoy>0?'positive':yoy<0?'negative':''}">${fmt(yoy,true)}${yoy==null?'':'%'}</div></div><div class="kpi"><div class="kpi-label">전월 대비</div><div class="kpi-value ${mom>0?'positive':mom<0?'negative':''}">${fmt(mom,true)}${mom==null?'':'%'}</div></div><div class="kpi"><div class="kpi-label">표시 기간 수집</div><div class="kpi-value">${recent}<span class="kpi-unit">/ ${months.length}개월</span></div></div></div><div class="tablehead"><span>최신월부터 · ${esc(unit(rows,s.metric))}</span><div class="toolbarbuttons"><button class="smallbtn" data-table="${item.id}">표 접기</button><button class="smallbtn" data-csv="${item.id}">CSV ↓</button></div></div><div class="tablewrap" id="table-${item.id}">${rowTable(rows,months,s.metric)}</div><details class="details"><summary>주요 수출국 · ${date(last)} 세계 수출 비중</summary><div class="countrychips">${countries.map(({c,v})=>`<button data-country="${c}">${esc(countryName(c))}<b>${fmt(item.series.WORLD[last]?.value>0?v/item.series.WORLD[last].value*100:null)}%</b></button>`).join('')}</div></details></article>`;
}
function render(){if(!data)return;const s=state(),months=windowMonths(data.latestMonth,s.range);let items=data.items.filter(i=>(group==='전체'||group==='관심'&&favorites.has(i.id)||i.group===group)&&(!s.query||(i.name+' '+i.hs.join(' ')+' '+i.note).toLowerCase().includes(s.query)));if(s.sort!=='default')items.sort((a,b)=>{const score=i=>{let rs=series(i,s.country);return s.sort==='value'?rs[data.latestMonth]?.value??-Infinity:change(rs[data.latestMonth]?.value,rs[priorYear(data.latestMonth)]?.value)??-Infinity};return score(b)-score(a)});$('#count').textContent=`${items.length}개 품목`;$('#cards').innerHTML=items.length?items.map(i=>panel(i,s,months)).join(''):'<div class="empty">해당하는 품목이 없습니다. 검색어나 분류를 바꿔주세요.</div>'}
function download(item){let s=state(),rows=series(item,s.country),ms=windowMonths(data.latestMonth,s.range);let body=[['월','품목','HS','국가','수출액(천 엔)','전년대비(%)','수량','수량단위','단가(엔/단위)'],...ms.map(m=>[m,item.name,item.hs.join('+'),countryName(s.country),rows[m]?.value??'',change(rows[m]?.value,rows[priorYear(m)]?.value)??'',rows[m]?.quantity??'',rows[m]?.unit??'',metricValue(rows[m],'price')??''])].map(r=>r.map(c=>'"'+String(c).replaceAll('"','""')+'"').join(',')).join('\r\n');let url=URL.createObjectURL(new Blob(['\ufeff'+body],{type:'text/csv;charset=utf-8;'})),a=document.createElement('a');a.href=url;a.download=`일본수출_${item.name}_${s.country}_${data.latestMonth}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('.controls').addEventListener('change',render);$('#search').addEventListener('input',render);$('.tabs').addEventListener('click',e=>{const b=e.target.closest('[data-group]');if(!b)return;group=b.dataset.group;$('.tabs .active')?.classList.remove('active');b.classList.add('active');render()});
$('#cards').addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.fav){let id=b.dataset.fav;favorites.has(id)?favorites.delete(id):favorites.add(id);try{localStorage.setItem('japan-export-favorites',JSON.stringify([...favorites]))}catch{}if(group==='관심')render();else{b.classList.toggle('on',favorites.has(id));b.textContent=favorites.has(id)?'★':'☆';b.setAttribute('aria-pressed',favorites.has(id))}}if(b.dataset.table){let t=$('#table-'+b.dataset.table);t.hidden=!t.hidden;b.textContent=t.hidden?'표 펼치기':'표 접기'}if(b.dataset.csv)download(data.items.find(i=>i.id===b.dataset.csv));if(b.dataset.country){$('#country').value=b.dataset.country;render();window.scrollTo({top:0,behavior:'smooth'})}});
document.addEventListener('pointermove',e=>{let t=e.target.closest?.('[data-tip]');if(!t){tooltip.style.display='none';return}tooltip.textContent=t.dataset.tip;tooltip.style.display='block';tooltip.style.left=Math.min(e.clientX+14,window.innerWidth-tooltip.offsetWidth-10)+'px';tooltip.style.top=Math.max(5,e.clientY-48)+'px'});
async function load(){try{let r=await fetch('data/exports.json.gz');if(!r.ok)throw Error('통계 파일을 불러올 수 없습니다.');data=await new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).json();if(!data.items?.length)throw Error('통계 데이터가 비어 있습니다.');const all=[...new Set(data.items.flatMap(i=>Object.keys(i.series)))].filter(c=>c!=='WORLD');all.sort((a,b)=>countryName(a).localeCompare(countryName(b),'ko'));$('#country').innerHTML='<option value="WORLD">세계 전체</option>'+all.map(c=>`<option value="${esc(c)}">${esc(countryName(c))}</option>`).join('');$('#period').textContent=`최신 ${fullDate(data.latestMonth)} · 5년 추적`;$('#checked').textContent=`확인 ${new Date(data.checkedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})} KST`;$('#sources').innerHTML=data.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.label.replace(/CSV.*$/,''))} ↗</a>`).join('');render();try{let r=await fetch('data/status.json',{cache:'no-store'});if(r.ok){let st=await r.json();if(!st.ok)$('#notice').innerHTML='<div class="warning">최근 수집에 실패해 마지막으로 검증된 데이터를 표시합니다. 원자료 확인이 재개되면 자동으로 갱신됩니다.</div>'}}catch{}}catch(e){$('#cards').innerHTML=`<div class="empty error">${esc(e.message)}<br>잠시 후 새로고침해 주세요.</div>`}}
load();
