const {readFileSync} = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = readFileSync('build.py', 'utf8').split('function renderBars() {')[1].split('/* ── 전체 표')[0];
const svg = {style:{}, innerHTML:'', setAttribute(k,v){this[k]=v;}};
const viewport = {clientWidth:360, scrollLeft:0, dataset:{}};
const dates = Array.from({length:365}, (_,i)=>new Date(Date.UTC(2026,0,i+1)).toISOString().slice(0,10));
const context = {document:{getElementById:id=>id==='bars'?svg:viewport}, onMkts:()=>['JP'], D:{okDays:{JP:dates}}, byDate:new Map(dates.map(d=>[d,[1,2]])), week:'2026-10-01', weekDays:w=>[w]};
vm.createContext(context);
vm.runInContext('function renderBars() {'+source, context);
context.renderBars();
assert.ok(parseFloat(svg.style.width)>=365*48, 'a year of dates must not shrink into one viewport');
assert.ok(!svg.innerHTML.includes('rotate('), 'dates should be horizontal');
assert.ok(svg.innerHTML.includes('2026'), 'year must be visible');
assert.ok(viewport.scrollLeft>10000, 'initial viewport should show the selected week');
viewport.scrollLeft=500;
context.renderBars();
assert.equal(viewport.scrollLeft,500,'routine refresh preserves manual scrolling');
context.week='2026-01-01';
context.renderBars();
assert.equal(viewport.scrollLeft,0,'week navigation refocuses chart');
context.D.okDays.JP=[];
context.renderBars();
assert.equal(svg.innerHTML,'');
assert.ok(parseFloat(svg.style.width)<=360,'empty chart clears stale width');
console.log('daily chart: dense dates, focus, preserved scroll, empty state passed');
