const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync('build.py','utf8').split("let mnView = 'compare';")[1].split('function mnPctText')[0];
let board = null;
const host = {querySelector:()=>board, set innerHTML(v){this.html=v; board={scrollWidth:2250,scrollLeft:0,scrollTop:0,addEventListener(){}};}};
const select={value:'cap',querySelector:()=>({})};
const els = {mnList:host,mnSort:select,mnQ:{value:''},mnCap:{value:'0'},mnNum:{checked:false},mnMeta:{},mnCnt:{}};
const rows=[['a',10,110],['b',5,90],['c',0,null],['d',20,100]].map(([code,cap,v])=>({code,cap,ko:code,orig:code,rows:[[]],series:new Map([['2026-09',[null,null,v]]])}));
const MNUM=Object.fromEntries(rows.map(x=>[x.code,{historyVerified:true,m:[['2026-09',null,x.series.get('2026-09')[2]]]}]));
const ctx={document:{getElementById:id=>els[id]},MNUM,MN_B:2026*12+8,D:{usdKrw:1400},mnCompanyRows:()=>new Map(rows.map(x=>[x.code,{...x}])),esc:String};
vm.createContext(ctx);vm.runInContext("let mnView = 'compare';"+source,ctx);
const ids=()=>[...host.html.matchAll(/class="mncompany" data-mcode="(.*?)"/g)].map(m=>m[1]);
ctx.renderMonthly(); assert.deepEqual(ids(),['d','a','b','c']); assert.equal(board.scrollLeft,2250);
board.scrollLeft=850;board.scrollTop=200;
ctx.mnHeaderSort('2026-09');assert.deepEqual(ids(),['a','d','b','c']);assert.equal(board.scrollLeft,850);assert.equal(board.scrollTop,200);
ctx.mnHeaderSort('2026-09');assert.deepEqual(ids(),['b','d','a','c']);assert.ok(host.html.includes('aria-sort="ascending"'));
ctx.mnHeaderSort('cap');assert.deepEqual(ids(),['d','a','b','c']);
ctx.mnHeaderSort('cap');assert.deepEqual(ids(),['b','a','d','c']);
ctx.mnHeaderSort('2026-08');assert.deepEqual(ids(),['d','a','b','c']);
console.log('monthly table: signed/zero/missing values, sort toggles, initial latest and preserved scroll passed');
